apiVersion: v1
kind: Service
metadata:
  name: pod-service
spec:
  selector:
    app: my-pod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30007
  type: NodePort
