apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-2
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80


