# apiVersion: v1
# kind: Pod
# metadata:
#   name: my-pod
# spec:
#   containers:
#     - name: my-container
#       image: rahuljat/simple-node-app
#       ports:
#         - containerPort: 3000

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pod-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-pod
  template:
    metadata:
      labels:
        app: my-pod
    spec:
      containers:
        - name: my-container
          image: rahuljat/simple-node-app
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: env-file
              readOnly: true
              mountPath: "/app/"
      volumes:
        - name: env-file
          secret:
            secretName: dotfile-secret
